### PR TITLE
add fennel dtb files

### PR DESCRIPTION
**Pull request by chinh4thepro**
this might fix it

### CODE REVIEW

**Comment by BenjaminWegener** [comment]
thanks, must have missed the notification, will check out ASAP

**Comment by BenjaminWegener** [comment]
got the same error as always:
[kern.log](https://github.com/BenjaminWegener/Cadmium-FENNEL14/files/8502100/kern.log)
suspecting the model is still missing - its this one https://www.lenovo.com/us/en/p/laptops/lenovo/lenovo-edu-chromebooks/lenovo-chromebook-3-(14”,-mediatek)-laptop/len101l0002

**Comment by chinh4thepro** [comment]
> 

this has already been added in "mt8183-kukui-jacuzzi-fennel14.dts"

**Comment by BenjaminWegener** [comment]
I am a little confused, do you think i have to add the https://chromium.googlesource.com/chromiumos/third_party/kernel/+/chromeos-4.19/arch/arm64/boot/dts/mediatek/mt8183-kukui-fennel14-sku0.dts somewhere ? At boot time the kernel doesnt find the command "cros_secure", so i was thinking, maybe some directory doesnt get mounted right.

**Comment by chinh4thepro** [comment]
you could try asking maya

**Pull request merged**
